"""Read-only client for Lightning Bolt's reverse-engineered API."""

from lightning_bolt_api.client import AuthenticationError, LightningBoltClient, LightningBoltError
from lightning_bolt_api.models import (
    ActivityFeed,
    ActivityFeedItem,
    Assignment,
    AssignmentOrigin,
    Dashboard,
    Department,
    DiscoveredContext,
    EmployeeMatch,
    OpenShiftGroup,
    OpenShiftGroupSummary,
    OpenShiftSummary,
    Personnel,
    SessionState,
    ShiftTrade,
    ShiftTradeSummary,
    Slot,
    SlotHistoryEntry,
    Subscription,
    Template,
    View,
    ViewerApiResponse,
)

__all__ = [
    "ActivityFeed",
    "ActivityFeedItem",
    "Assignment",
    "AssignmentOrigin",
    "AuthenticationError",
    "Dashboard",
    "Department",
    "DiscoveredContext",
    "EmployeeMatch",
    "LightningBoltClient",
    "LightningBoltError",
    "OpenShiftGroup",
    "OpenShiftGroupSummary",
    "OpenShiftSummary",
    "Personnel",
    "SessionState",
    "ShiftTrade",
    "ShiftTradeSummary",
    "Slot",
    "SlotHistoryEntry",
    "Subscription",
    "Template",
    "View",
    "ViewerApiResponse",
]
